export const env = {
    POSITION_STACK_FORWARD_URL: process.env.POSITION_STACK_FORWARD_URL,
    POSITION_STACK_REVERSE_URL: process.env.POSITION_STACK_REVERSE_URL,
    POSITION_STACK_ACCESS_KEY: process.env.POSITION_STACK_ACCESS_KEY,
    LOCATION_IQ_ACESS_KEY: process.env.LOCATION_IQ_ACESS_KEY,
    LOCATION_IQ_URL: process.env.LOCATION_IQ_URL,
    USE_PROVIDER_LOCATION: process.env.USE_PROVIDER_LOCATION,
}