export const env = {
    POSITION_STACK_FORWARD_URL: process.env.POSITION_STACK_FORWARD_URL,
    POSITION_STACK_REVERSE_URL: process.env.POSITION_STACK_REVERSE_URL,
    POSITION_STACK_ACCESS_KEY: process.env.POSITION_STACK_ACCESS_KEY
}